version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
