linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gofumpt
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign

linters-settings:
  govet:
    enable-all: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
